[2023-02-14T21:50:53.540-0300] {processor.py:153} INFO - Started process (PID=4824) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:50:53.541-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T21:50:53.541-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:50:53.541-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:50:53.647-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:50:53.647-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:50:53.647-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:50:53.672-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.133 seconds
[2023-02-14T21:51:24.101-0300] {processor.py:153} INFO - Started process (PID=4994) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:51:24.101-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T21:51:24.102-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:51:24.102-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:51:24.200-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:51:24.200-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:51:24.200-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:51:24.308-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.208 seconds
[2023-02-14T21:51:54.820-0300] {processor.py:153} INFO - Started process (PID=5092) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:51:54.821-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T21:51:54.822-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:51:54.821-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:51:55.070-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:51:55.070-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:51:55.071-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:51:55.086-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.268 seconds
[2023-02-14T21:52:25.805-0300] {processor.py:153} INFO - Started process (PID=5215) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:52:25.806-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T21:52:25.806-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:52:25.806-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:52:26.102-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:52:26.102-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:52:26.103-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:52:26.127-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.324 seconds
[2023-02-14T21:52:56.743-0300] {processor.py:153} INFO - Started process (PID=5321) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:52:56.744-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T21:52:56.744-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:52:56.744-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:52:56.934-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:52:56.933-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:52:56.934-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:52:56.949-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.208 seconds
[2023-02-14T21:53:23.267-0300] {processor.py:153} INFO - Started process (PID=5589) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:53:23.267-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T21:53:23.268-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:53:23.268-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:53:23.371-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:53:23.370-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:53:23.371-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:53:23.397-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.132 seconds
[2023-02-14T21:53:53.676-0300] {processor.py:153} INFO - Started process (PID=5681) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:53:53.677-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T21:53:53.677-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:53:53.677-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:53:53.801-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:53:53.800-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:53:53.801-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:53:53.822-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.148 seconds
[2023-02-14T21:54:24.236-0300] {processor.py:153} INFO - Started process (PID=5791) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:54:24.237-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T21:54:24.237-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:54:24.237-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:54:24.436-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:54:24.436-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:54:24.436-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:54:24.451-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.217 seconds
[2023-02-14T21:54:56.554-0300] {processor.py:153} INFO - Started process (PID=6123) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:54:56.554-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T21:54:56.555-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:54:56.554-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:54:56.685-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:54:56.685-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:54:56.686-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:54:56.714-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.162 seconds
[2023-02-14T21:55:26.952-0300] {processor.py:153} INFO - Started process (PID=6230) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:55:26.953-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T21:55:26.953-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:55:26.953-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:55:27.058-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:55:27.058-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:55:27.058-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:55:27.093-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.142 seconds
[2023-02-14T21:55:57.651-0300] {processor.py:153} INFO - Started process (PID=6328) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:55:57.651-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T21:55:57.652-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:55:57.652-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:55:57.885-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:55:57.885-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:55:57.885-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:55:57.900-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.252 seconds
[2023-02-14T21:56:28.676-0300] {processor.py:153} INFO - Started process (PID=6428) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:56:28.677-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T21:56:28.678-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:56:28.678-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:56:28.892-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:56:28.891-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:56:28.892-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:56:28.907-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.233 seconds
[2023-02-14T21:56:59.631-0300] {processor.py:153} INFO - Started process (PID=6529) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:56:59.632-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T21:56:59.632-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:56:59.632-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:56:59.937-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:56:59.936-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:56:59.938-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:56:59.957-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.328 seconds
[2023-02-14T21:57:30.599-0300] {processor.py:153} INFO - Started process (PID=6633) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:57:30.609-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T21:57:30.610-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:57:30.610-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:57:30.719-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:57:30.718-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:57:30.719-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:57:30.737-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.139 seconds
[2023-02-14T21:58:01.045-0300] {processor.py:153} INFO - Started process (PID=6740) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:58:01.046-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T21:58:01.046-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:58:01.046-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:58:01.148-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:58:01.147-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:58:01.148-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:58:01.164-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.120 seconds
[2023-02-14T21:58:31.781-0300] {processor.py:153} INFO - Started process (PID=6847) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:58:31.782-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T21:58:31.782-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:58:31.782-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:58:31.898-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:58:31.898-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:58:31.898-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:58:32.012-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.233 seconds
[2023-02-14T21:59:02.639-0300] {processor.py:153} INFO - Started process (PID=6947) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:59:02.640-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T21:59:02.640-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:59:02.640-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:59:02.905-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:59:02.905-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:59:02.906-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:59:02.931-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.295 seconds
[2023-02-14T21:59:33.605-0300] {processor.py:153} INFO - Started process (PID=7052) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:59:33.606-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T21:59:33.606-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:59:33.606-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:59:33.917-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:59:33.916-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:59:33.917-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T21:59:33.936-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.333 seconds
[2023-02-14T22:01:58.823-0300] {processor.py:153} INFO - Started process (PID=7414) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:01:58.824-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:01:58.824-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:01:58.824-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:01:58.929-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:01:58.928-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:01:58.929-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:01:58.945-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.124 seconds
[2023-02-14T22:02:30.121-0300] {processor.py:153} INFO - Started process (PID=7588) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:02:30.122-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:02:30.123-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:02:30.123-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:02:30.225-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:02:30.224-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:02:30.225-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:02:30.240-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.121 seconds
[2023-02-14T22:02:36.282-0300] {processor.py:153} INFO - Started process (PID=7799) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:02:36.282-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:02:36.282-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:02:36.282-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:02:36.386-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:02:36.386-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:02:36.387-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:02:36.404-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.125 seconds
[2023-02-14T22:03:07.606-0300] {processor.py:153} INFO - Started process (PID=7890) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:03:07.607-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:03:07.607-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:03:07.607-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:03:07.736-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:03:07.735-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:03:07.736-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:03:07.756-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.152 seconds
[2023-02-14T22:03:38.164-0300] {processor.py:153} INFO - Started process (PID=7983) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:03:38.165-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:03:38.166-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:03:38.166-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:03:38.448-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:03:38.448-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:03:38.449-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:03:38.463-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.301 seconds
[2023-02-14T22:04:08.987-0300] {processor.py:153} INFO - Started process (PID=8077) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:04:08.988-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:04:08.988-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:04:08.988-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:04:09.262-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:04:09.262-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:04:09.263-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:04:09.282-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.297 seconds
[2023-02-14T22:04:40.045-0300] {processor.py:153} INFO - Started process (PID=8169) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:04:40.045-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:04:40.046-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:04:40.046-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:04:40.331-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:04:40.330-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:04:40.331-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:04:40.349-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.307 seconds
[2023-02-14T22:05:10.970-0300] {processor.py:153} INFO - Started process (PID=8266) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:05:10.971-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:05:10.971-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:05:10.971-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:05:11.092-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:05:11.091-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:05:11.092-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:05:11.112-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.145 seconds
[2023-02-14T22:05:41.402-0300] {processor.py:153} INFO - Started process (PID=8358) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:05:41.403-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:05:41.403-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:05:41.403-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:05:41.522-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:05:41.522-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:05:41.523-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:05:41.542-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.142 seconds
[2023-02-14T22:06:12.244-0300] {processor.py:153} INFO - Started process (PID=8454) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:06:12.244-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:06:12.245-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:06:12.245-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:06:12.344-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:06:12.344-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:06:12.345-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:06:12.446-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.204 seconds
[2023-02-14T22:06:43.234-0300] {processor.py:153} INFO - Started process (PID=8574) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:06:43.234-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:06:43.235-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:06:43.235-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:06:43.459-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:06:43.459-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:06:43.459-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:06:43.474-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.243 seconds
[2023-02-14T22:07:17.161-0300] {processor.py:153} INFO - Started process (PID=8846) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:07:17.162-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:07:17.162-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:07:17.162-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:07:17.276-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:07:17.276-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:07:17.277-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:07:17.293-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.134 seconds
[2023-02-14T22:07:48.469-0300] {processor.py:153} INFO - Started process (PID=8938) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:07:48.470-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:07:48.470-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:07:48.470-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:07:48.591-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:07:48.590-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:07:48.591-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:07:48.613-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.146 seconds
[2023-02-14T22:08:19.082-0300] {processor.py:153} INFO - Started process (PID=9032) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:08:19.082-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:08:19.083-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:08:19.083-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:08:19.375-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:08:19.374-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:08:19.375-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:08:19.395-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.316 seconds
[2023-02-14T22:08:50.168-0300] {processor.py:153} INFO - Started process (PID=9123) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:08:50.169-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:08:50.169-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:08:50.169-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:08:50.462-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:08:50.462-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:08:50.462-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:08:50.486-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.320 seconds
[2023-02-14T22:09:21.321-0300] {processor.py:153} INFO - Started process (PID=9220) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:09:21.322-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:09:21.323-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:09:21.323-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:09:21.573-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:09:21.573-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:09:21.573-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:09:21.597-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.278 seconds
[2023-02-14T22:09:52.004-0300] {processor.py:153} INFO - Started process (PID=9309) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:09:52.004-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:09:52.005-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:09:52.005-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:09:52.126-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:09:52.125-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:09:52.126-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:09:52.145-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.144 seconds
[2023-02-14T22:10:22.337-0300] {processor.py:153} INFO - Started process (PID=9405) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:10:22.338-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:10:22.339-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:10:22.339-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:10:22.462-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:10:22.462-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:10:22.463-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:10:22.483-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.148 seconds
[2023-02-14T22:10:52.974-0300] {processor.py:153} INFO - Started process (PID=9526) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:10:52.975-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:10:52.975-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:10:52.975-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:10:53.082-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:10:53.082-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:10:53.083-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:10:53.185-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.213 seconds
[2023-02-14T22:11:24.090-0300] {processor.py:153} INFO - Started process (PID=9629) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:11:24.090-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:11:24.091-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:11:24.091-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:11:24.273-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:11:24.273-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:11:24.274-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:11:24.297-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.209 seconds
[2023-02-14T22:11:55.069-0300] {processor.py:153} INFO - Started process (PID=9735) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:11:55.070-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:11:55.070-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:11:55.070-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:11:55.315-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:11:55.314-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:11:55.315-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:11:55.330-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.264 seconds
[2023-02-14T22:12:25.686-0300] {processor.py:153} INFO - Started process (PID=9842) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:12:25.687-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:12:25.687-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:12:25.687-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:12:25.809-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:12:25.808-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:12:25.809-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:12:25.837-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.153 seconds
[2023-02-14T22:12:56.025-0300] {processor.py:153} INFO - Started process (PID=9941) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:12:56.026-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:12:56.026-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:12:56.026-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:12:56.130-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:12:56.129-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:12:56.130-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:12:56.147-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.123 seconds
[2023-02-14T22:13:26.503-0300] {processor.py:153} INFO - Started process (PID=10259) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:13:26.504-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:13:26.504-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:13:26.504-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:13:26.735-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:13:26.735-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:13:26.736-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:13:26.762-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.261 seconds
[2023-02-14T22:13:57.197-0300] {processor.py:153} INFO - Started process (PID=10368) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:13:57.198-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:13:57.198-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:13:57.198-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:13:57.495-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:13:57.494-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:13:57.495-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:13:57.517-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.322 seconds
[2023-02-14T22:14:27.919-0300] {processor.py:153} INFO - Started process (PID=10462) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:14:27.920-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:14:27.920-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:14:27.920-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:14:28.122-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:14:28.121-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:14:28.122-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:14:28.147-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.230 seconds
[2023-02-14T22:14:58.295-0300] {processor.py:153} INFO - Started process (PID=10552) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:14:58.296-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:14:58.296-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:14:58.296-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:14:58.498-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:14:58.497-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:14:58.498-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:14:58.521-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.229 seconds
[2023-02-14T22:15:29.103-0300] {processor.py:153} INFO - Started process (PID=10645) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:15:29.104-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:15:29.104-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:15:29.104-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:15:29.225-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:15:29.225-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:15:29.226-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:15:29.246-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.145 seconds
[2023-02-14T22:15:59.449-0300] {processor.py:153} INFO - Started process (PID=10738) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:15:59.450-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:15:59.450-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:15:59.450-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:15:59.573-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:15:59.572-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:15:59.573-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:15:59.603-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.156 seconds
[2023-02-14T22:16:30.315-0300] {processor.py:153} INFO - Started process (PID=10830) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:16:30.316-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:16:30.317-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:16:30.316-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:16:30.619-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:16:30.619-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:16:30.620-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:16:30.640-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.327 seconds
[2023-02-14T22:17:01.474-0300] {processor.py:153} INFO - Started process (PID=10930) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:17:01.475-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:17:01.476-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:17:01.476-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:17:01.699-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:17:01.699-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:17:01.700-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:17:01.723-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.251 seconds
[2023-02-14T22:17:31.828-0300] {processor.py:153} INFO - Started process (PID=11026) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:17:31.829-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:17:31.830-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:17:31.829-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:17:32.023-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:17:32.022-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:17:32.023-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:17:32.038-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.212 seconds
[2023-02-14T22:18:02.796-0300] {processor.py:153} INFO - Started process (PID=11118) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:18:02.796-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:18:02.797-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:18:02.797-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:18:03.088-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:18:03.087-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:18:03.088-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:18:03.116-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.323 seconds
[2023-02-14T22:18:33.675-0300] {processor.py:153} INFO - Started process (PID=11211) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:18:33.676-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:18:33.676-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:18:33.676-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:18:33.797-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:18:33.796-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:18:33.797-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:18:33.826-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.153 seconds
[2023-02-14T22:19:04.309-0300] {processor.py:153} INFO - Started process (PID=11304) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:19:04.310-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:19:04.311-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:19:04.311-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:19:04.609-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:19:04.609-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:19:04.609-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:19:04.629-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.322 seconds
[2023-02-14T22:19:35.437-0300] {processor.py:153} INFO - Started process (PID=11401) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:19:35.438-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:19:35.438-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:19:35.438-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:19:35.641-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:19:35.640-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:19:35.641-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:19:35.666-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.232 seconds
[2023-02-14T22:24:16.612-0300] {processor.py:153} INFO - Started process (PID=11768) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:24:16.613-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:24:16.613-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:24:16.613-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:24:16.748-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:24:16.747-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:24:16.748-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:24:16.778-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.169 seconds
[2023-02-14T22:24:46.959-0300] {processor.py:153} INFO - Started process (PID=11925) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:24:46.960-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:24:46.961-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:24:46.960-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:24:47.092-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:24:47.092-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:24:47.093-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:24:47.121-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.165 seconds
[2023-02-14T22:24:57.755-0300] {processor.py:153} INFO - Started process (PID=12182) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:24:57.755-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:24:57.755-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:24:57.755-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:24:57.856-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:24:57.855-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:24:57.856-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:24:57.881-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.128 seconds
[2023-02-14T22:26:11.043-0300] {processor.py:153} INFO - Started process (PID=12495) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:26:11.043-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:26:11.044-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:26:11.044-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:26:11.154-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:26:11.153-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:26:11.154-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:26:11.178-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.137 seconds
[2023-02-14T22:27:31.640-0300] {processor.py:153} INFO - Started process (PID=12866) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:27:31.641-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:27:31.641-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:27:31.641-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:27:31.750-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:27:31.749-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:27:31.750-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:27:31.778-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.140 seconds
[2023-02-14T22:28:02.336-0300] {processor.py:153} INFO - Started process (PID=12976) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:28:02.336-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:28:02.337-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:28:02.337-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:28:02.461-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:28:02.461-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:28:02.462-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:28:02.488-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.154 seconds
[2023-02-14T22:28:10.963-0300] {processor.py:153} INFO - Started process (PID=13234) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:28:10.964-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:28:10.964-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:28:10.964-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:28:11.074-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:28:11.073-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:28:11.074-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:28:11.091-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.130 seconds
[2023-02-14T22:28:41.456-0300] {processor.py:153} INFO - Started process (PID=13331) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:28:41.457-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:28:41.457-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:28:41.457-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:28:41.590-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:28:41.589-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:28:41.590-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:28:41.611-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.157 seconds
[2023-02-14T22:29:12.040-0300] {processor.py:153} INFO - Started process (PID=13426) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:29:12.041-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:29:12.042-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:29:12.042-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:29:12.253-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:29:12.253-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:29:12.254-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:29:12.269-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.231 seconds
[2023-02-14T22:29:43.367-0300] {processor.py:153} INFO - Started process (PID=13545) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:29:43.368-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:29:43.369-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:29:43.369-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:29:43.695-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:29:43.694-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:29:43.695-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:29:43.715-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.351 seconds
[2023-02-14T22:30:07.330-0300] {processor.py:153} INFO - Started process (PID=13814) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:30:07.331-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:30:07.331-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:30:07.331-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:30:07.462-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:30:07.462-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:30:07.463-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:30:07.488-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.160 seconds
[2023-02-14T22:30:37.777-0300] {processor.py:153} INFO - Started process (PID=13912) to work on /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:30:37.777-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_uniprot.py for tasks to queue
[2023-02-14T22:30:37.778-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:30:37.778-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:30:37.905-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:30:37.904-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_uniprot.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_uniprot.py", line 7, in <module>
    from scripts.uniprot import download, extract_jsons, join_antibodies, drop_columns_antibody, drop_columns_antigen
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 5, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:30:37.905-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_uniprot.py
[2023-02-14T22:30:37.927-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_uniprot.py took 0.152 seconds
