[2022-12-14T18:31:56.827-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: download_uniprot.extract_files manual__2022-12-14T21:31:55.246085+00:00 [queued]>
[2022-12-14T18:31:56.840-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: download_uniprot.extract_files manual__2022-12-14T21:31:55.246085+00:00 [queued]>
[2022-12-14T18:31:56.840-0300] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-14T18:31:56.840-0300] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-14T18:31:56.840-0300] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-14T18:31:56.853-0300] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_files> on 2022-12-14 21:31:55.246085+00:00
[2022-12-14T18:31:56.858-0300] {standard_task_runner.py:55} INFO - Started process 30507 to run task
[2022-12-14T18:31:56.859-0300] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_uniprot', 'extract_files', 'manual__2022-12-14T21:31:55.246085+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/download_uniprot.py', '--cfg-path', '/tmp/tmpaect9vh6']
[2022-12-14T18:31:56.860-0300] {standard_task_runner.py:83} INFO - Job 6: Subtask extract_files
[2022-12-14T18:31:56.932-0300] {task_command.py:389} INFO - Running <TaskInstance: download_uniprot.extract_files manual__2022-12-14T21:31:55.246085+00:00 [running]> on host kallo-Ubuntu
[2022-12-14T18:31:57.012-0300] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Kallox
AIRFLOW_CTX_DAG_ID=download_uniprot
AIRFLOW_CTX_TASK_ID=extract_files
AIRFLOW_CTX_EXECUTION_DATE=2022-12-14T21:31:55.246085+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-14T21:31:55.246085+00:00
[2022-12-14T18:31:57.012-0300] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: extract() missing 1 required positional argument: 'filename'
[2022-12-14T18:31:57.023-0300] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=download_uniprot, task_id=extract_files, execution_date=20221214T213155, start_date=20221214T213156, end_date=20221214T213157
[2022-12-14T18:31:57.035-0300] {standard_task_runner.py:105} ERROR - Failed to execute job 6 for task extract_files (extract() missing 1 required positional argument: 'filename'; 30507)
[2022-12-14T18:31:57.071-0300] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-14T18:31:57.094-0300] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
