[2022-12-29T17:26:59.990-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: download_catnap.download_files scheduled__2022-11-03T00:00:00+00:00 [queued]>
[2022-12-29T17:27:00.011-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: download_catnap.download_files scheduled__2022-11-03T00:00:00+00:00 [queued]>
[2022-12-29T17:27:00.011-0300] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-29T17:27:00.012-0300] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-29T17:27:00.012-0300] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-29T17:27:00.201-0300] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): download_files> on 2022-11-03 00:00:00+00:00
[2022-12-29T17:27:00.208-0300] {standard_task_runner.py:55} INFO - Started process 25046 to run task
[2022-12-29T17:27:00.213-0300] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_catnap', 'download_files', 'scheduled__2022-11-03T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/download_catnap.py', '--cfg-path', '/tmp/tmpgv5tafno']
[2022-12-29T17:27:00.215-0300] {standard_task_runner.py:83} INFO - Job 33: Subtask download_files
[2022-12-29T17:27:00.377-0300] {task_command.py:389} INFO - Running <TaskInstance: download_catnap.download_files scheduled__2022-11-03T00:00:00+00:00 [running]> on host kallo-Ubuntu
[2022-12-29T17:27:00.551-0300] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=download_catnap
AIRFLOW_CTX_TASK_ID=download_files
AIRFLOW_CTX_EXECUTION_DATE=2022-11-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-03T00:00:00+00:00
[2022-12-29T17:27:38.221-0300] {logging_mixin.py:137} INFO - Assay downloaded.
[2022-12-29T17:27:38.232-0300] {logging_mixin.py:137} INFO - Assay.tsv saved.
[2022-12-29T17:27:40.742-0300] {logging_mixin.py:137} INFO - Antibodies downloaded.
[2022-12-29T17:27:40.743-0300] {logging_mixin.py:137} INFO - Antibodies.tsv saved.
[2022-12-29T17:27:41.898-0300] {logging_mixin.py:137} INFO - Antibodies_germlines downloaded.
[2022-12-29T17:27:41.900-0300] {logging_mixin.py:137} INFO - Antibodies_germlines.tsv saved.
[2022-12-29T17:27:43.808-0300] {logging_mixin.py:137} INFO - Antibody_heavy_chain_na_sequences downloaded.
[2022-12-29T17:27:43.809-0300] {logging_mixin.py:137} INFO - Antibody_heavy_chain_na_sequences.fasta saved.
[2022-12-29T17:27:45.402-0300] {logging_mixin.py:137} INFO - Antibody_heavy_chain_aa_sequences downloaded.
[2022-12-29T17:27:45.403-0300] {logging_mixin.py:137} INFO - Antibody_heavy_chain_aa_sequences.fasta saved.
[2022-12-29T17:27:46.993-0300] {logging_mixin.py:137} INFO - Antibody_light_chain_na_sequences downloaded.
[2022-12-29T17:27:46.994-0300] {logging_mixin.py:137} INFO - Antibody_light_chain_na_sequences.fasta saved.
[2022-12-29T17:27:48.344-0300] {logging_mixin.py:137} INFO - Antibody_light_chain_aa_sequences downloaded.
[2022-12-29T17:27:48.346-0300] {logging_mixin.py:137} INFO - Antibody_light_chain_aa_sequences.fasta saved.
[2022-12-29T17:27:50.591-0300] {logging_mixin.py:137} INFO - Viruses downloaded.
[2022-12-29T17:27:50.592-0300] {logging_mixin.py:137} INFO - Viruses.tsv saved.
[2022-12-29T17:28:06.977-0300] {logging_mixin.py:137} INFO - Virus_na_alignment downloaded.
[2022-12-29T17:28:06.987-0300] {logging_mixin.py:137} INFO - Virus_na_alignment.tsv saved.
[2022-12-29T17:28:11.119-0300] {local_task_job.py:224} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-12-29T17:28:11.128-0300] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 25046. PIDs of all processes in the group: [25046]
[2022-12-29T17:28:11.128-0300] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 25046
[2022-12-29T17:28:11.128-0300] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-12-29T17:28:11.180-0300] {process_utils.py:79} INFO - Process psutil.Process(pid=25046, status='terminated', exitcode=0, started='17:26:59') (25046) terminated with exit code 0
