[2023-01-01T20:30:46.929-0300] {processor.py:153} INFO - Started process (PID=3656) to work on /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-01T20:30:46.929-0300] {processor.py:743} INFO - Processing file /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-01T20:30:46.930-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:30:46.930-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-01T20:30:46.942-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:30:46.941-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-01T20:30:46.942-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:30:46.942-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-01T20:30:46.942-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-01T20:30:46.956-0300] {processor.py:175} INFO - Processing /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-01-01T20:31:18.118-0300] {processor.py:153} INFO - Started process (PID=4921) to work on /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-01T20:31:18.119-0300] {processor.py:743} INFO - Processing file /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-01T20:31:18.120-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:31:18.119-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-01T20:31:18.139-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:31:18.138-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-01T20:31:18.140-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:31:18.140-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-01T20:31:18.140-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-01T20:31:18.156-0300] {processor.py:175} INFO - Processing /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2023-01-01T20:31:48.888-0300] {processor.py:153} INFO - Started process (PID=5300) to work on /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-01T20:31:48.889-0300] {processor.py:743} INFO - Processing file /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-01T20:31:48.889-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:31:48.889-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-01T20:31:48.902-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:31:48.902-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-01T20:31:48.902-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:31:48.902-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-01T20:31:48.902-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-01T20:31:48.916-0300] {processor.py:175} INFO - Processing /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2023-01-01T20:32:19.345-0300] {processor.py:153} INFO - Started process (PID=5662) to work on /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-01T20:32:19.345-0300] {processor.py:743} INFO - Processing file /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-01T20:32:19.346-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:32:19.346-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-01T20:32:19.357-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:32:19.357-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-01T20:32:19.358-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:32:19.358-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-01T20:32:19.358-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-01T20:32:19.372-0300] {processor.py:175} INFO - Processing /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-01-01T20:32:50.917-0300] {processor.py:153} INFO - Started process (PID=5975) to work on /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-01T20:32:50.918-0300] {processor.py:743} INFO - Processing file /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-01T20:32:50.918-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:32:50.918-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-01T20:32:50.930-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:32:50.929-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-01T20:32:50.930-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:32:50.930-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-01T20:32:50.930-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-01T20:32:50.945-0300] {processor.py:175} INFO - Processing /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-01-01T20:33:21.797-0300] {processor.py:153} INFO - Started process (PID=6277) to work on /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-01T20:33:21.798-0300] {processor.py:743} INFO - Processing file /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-01T20:33:21.799-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:33:21.799-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-01T20:33:21.810-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:33:21.810-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-01T20:33:21.810-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:33:21.810-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-01T20:33:21.811-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-01T20:33:21.827-0300] {processor.py:175} INFO - Processing /home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
