[2022-12-14T21:43:47.981-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: download_uniprot.extract_files manual__2022-12-15T00:43:45.917872+00:00 [queued]>
[2022-12-14T21:43:47.993-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: download_uniprot.extract_files manual__2022-12-15T00:43:45.917872+00:00 [queued]>
[2022-12-14T21:43:47.993-0300] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-14T21:43:47.994-0300] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-14T21:43:47.994-0300] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-14T21:43:48.005-0300] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_files> on 2022-12-15 00:43:45.917872+00:00
[2022-12-14T21:43:48.009-0300] {standard_task_runner.py:55} INFO - Started process 140769 to run task
[2022-12-14T21:43:48.013-0300] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_uniprot', 'extract_files', 'manual__2022-12-15T00:43:45.917872+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/download_uniprot.py', '--cfg-path', '/tmp/tmpbvfqqedh']
[2022-12-14T21:43:48.014-0300] {standard_task_runner.py:83} INFO - Job 17: Subtask extract_files
[2022-12-14T21:43:48.087-0300] {task_command.py:389} INFO - Running <TaskInstance: download_uniprot.extract_files manual__2022-12-15T00:43:45.917872+00:00 [running]> on host kallo-Ubuntu
[2022-12-14T21:43:48.159-0300] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Kallox
AIRFLOW_CTX_DAG_ID=download_uniprot
AIRFLOW_CTX_TASK_ID=extract_files
AIRFLOW_CTX_EXECUTION_DATE=2022-12-15T00:43:45.917872+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-15T00:43:45.917872+00:00
[2022-12-14T21:43:58.580-0300] {logging_mixin.py:137} INFO - 3000
[2022-12-14T21:44:01.161-0300] {logging_mixin.py:137} INFO - 4000
[2022-12-14T21:44:05.305-0300] {logging_mixin.py:137} INFO - 5000
[2022-12-14T21:44:10.215-0300] {logging_mixin.py:137} INFO - 7000
[2022-12-14T21:44:12.926-0300] {logging_mixin.py:137} INFO - 8000
[2022-12-14T21:44:18.503-0300] {logging_mixin.py:137} INFO - 11000
[2022-12-14T21:44:23.425-0300] {logging_mixin.py:137} INFO - 12000
[2022-12-14T21:44:29.175-0300] {logging_mixin.py:137} INFO - 13000
[2022-12-14T21:44:37.291-0300] {logging_mixin.py:137} INFO - 14000
[2022-12-14T21:44:45.674-0300] {logging_mixin.py:137} INFO - 15000
[2022-12-14T21:44:54.106-0300] {logging_mixin.py:137} INFO - 16000
[2022-12-14T21:45:03.545-0300] {logging_mixin.py:137} INFO - 17000
[2022-12-14T21:45:09.235-0300] {local_task_job.py:224} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-12-14T21:45:09.245-0300] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 140769. PIDs of all processes in the group: [140769]
[2022-12-14T21:45:09.245-0300] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 140769
[2022-12-14T21:45:09.248-0300] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-12-14T21:45:10.472-0300] {process_utils.py:79} INFO - Process psutil.Process(pid=140769, status='terminated', exitcode=0, started='21:43:47') (140769) terminated with exit code 0
