[2023-01-04T22:25:32.402-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: download_covabdab.download_files scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2023-01-04T22:25:32.413-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: download_covabdab.download_files scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2023-01-04T22:25:32.413-0300] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T22:25:32.413-0300] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-04T22:25:32.414-0300] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T22:25:32.425-0300] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): download_files> on 2022-12-01 00:00:00+00:00
[2023-01-04T22:25:32.428-0300] {standard_task_runner.py:55} INFO - Started process 8857 to run task
[2023-01-04T22:25:32.430-0300] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_covabdab', 'download_files', 'scheduled__2022-12-01T00:00:00+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/download_covabdab.py', '--cfg-path', '/tmp/tmpdh3ys2zn']
[2023-01-04T22:25:32.431-0300] {standard_task_runner.py:83} INFO - Job 255: Subtask download_files
[2023-01-04T22:25:32.493-0300] {task_command.py:389} INFO - Running <TaskInstance: download_covabdab.download_files scheduled__2022-12-01T00:00:00+00:00 [running]> on host kallo-Ubuntu
[2023-01-04T22:25:32.561-0300] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Kallox
AIRFLOW_CTX_DAG_ID=download_covabdab
AIRFLOW_CTX_TASK_ID=download_files
AIRFLOW_CTX_EXECUTION_DATE=2022-12-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-01T00:00:00+00:00
[2023-01-04T22:25:34.183-0300] {logging_mixin.py:137} INFO - 20th December, 2022
[2023-01-04T22:25:34.184-0300] {logging_mixin.py:137} INFO - http://opig.stats.ox.ac.uk/webapps/covabdab/static/downloads/CoV-AbDab_201222.csv
[2023-01-04T22:25:37.564-0300] {logging_mixin.py:137} INFO - url descargada
[2023-01-04T22:25:37.580-0300] {python.py:177} INFO - Done. Returned value was: None
[2023-01-04T22:25:37.598-0300] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=download_covabdab, task_id=download_files, execution_date=20221201T000000, start_date=20230105T012532, end_date=20230105T012537
[2023-01-04T22:25:38.608-0300] {standard_task_runner.py:105} ERROR - Failed to execute job 255 for task download_files ((psycopg2.errors.DeadlockDetected) deadlock detected
DETAIL:  Process 8883 waits for ShareLock on transaction 301412; blocked by process 8777.
Process 8777 waits for ShareLock on transaction 301411; blocked by process 8883.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (2,8) in relation "dag_run"

[SQL: UPDATE dag_run SET last_scheduling_decision=%(last_scheduling_decision)s, updated_at=%(updated_at)s WHERE dag_run.id = %(dag_run_id)s]
[parameters: {'last_scheduling_decision': datetime.datetime(2023, 1, 5, 1, 25, 31, 785631, tzinfo=Timezone('UTC')), 'updated_at': datetime.datetime(2023, 1, 5, 1, 25, 31, 809012, tzinfo=Timezone('UTC')), 'dag_run_id': 106}]
(Background on this error at: https://sqlalche.me/e/14/e3q8); 8857)
[2023-01-04T22:25:38.641-0300] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-04T22:25:38.674-0300] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
